# Generated by Django 6.0.1 on 2026-01-31 03:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meal_name",
                    models.CharField(
                        help_text="Name of the meal (e.g., Vegetable Biryani, Dal Rice)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the meal", null=True
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        default="lunch",
                        max_length=20,
                    ),
                ),
                (
                    "meal_image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo of the meal",
                        null=True,
                        upload_to="meals/%Y/%m/%d/",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Number of servings available",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "original_quantity",
                    models.IntegerField(
                        editable=False,
                        help_text="Original quantity when meal was posted",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "serving_time",
                    models.TimeField(help_text="Time when meal will be served"),
                ),
                (
                    "serving_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date when meal will be served",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Address where meal can be collected", max_length=300
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        help_text="Latitude for location mapping",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=6,
                        help_text="Longitude for location mapping",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "proximity_radius",
                    models.FloatField(
                        default=5.0,
                        help_text="Radius in km for beneficiary search (default: 5km)",
                        validators=[django.core.validators.MinValueValidator(0.5)],
                    ),
                ),
                (
                    "provider_contact",
                    models.CharField(
                        blank=True,
                        help_text="Contact number of provider",
                        max_length=17,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether meal is currently available for claiming",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False, help_text="Whether meal serving time has passed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provided_meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MealClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_claimed",
                    models.IntegerField(
                        default=1,
                        help_text="Number of servings claimed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending OTP Verification"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                            ("collected", "Collected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("otp_sent", models.BooleanField(default=False)),
                ("otp_verified", models.BooleanField(default=False)),
                ("otp_sent_at", models.DateTimeField(blank=True, null=True)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_code",
                    models.CharField(
                        blank=True,
                        help_text="Unique code for meal pickup - generated after OTP verification",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("collection_notes", models.TextField(blank=True)),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claimed_meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="meals.meal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal Claim",
                "verbose_name_plural": "Meal Claims",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meals.mealclaim",
                    ),
                ),
                (
                    "related_meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="meals.meal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["serving_date", "serving_time"],
                name="meals_meal_serving_e9a20e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["is_active", "is_expired"], name="meals_meal_is_acti_03b987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meal",
            index=models.Index(
                fields=["latitude", "longitude"], name="meals_meal_latitud_fde7fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mealclaim",
            index=models.Index(fields=["status"], name="meals_mealc_status_41fbb8_idx"),
        ),
        migrations.AddIndex(
            model_name="mealclaim",
            index=models.Index(
                fields=["confirmation_code"], name="meals_mealc_confirm_816593_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mealclaim",
            unique_together={("meal", "beneficiary")},
        ),
    ]
