# Generated by Django 6.0.1 on 2026-01-31 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_meal_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="proximity_radius",
            field=models.FloatField(
                default=5.0,
                help_text="Radius in km for beneficiary search (default: 5km)",
                validators=[django.core.validators.MinValueValidator(0.5)],
            ),
        ),
    ]
